### ISSUE TITLE
indexing issue

### ISSUE THREAD

**Issue by josephhughes** [centre-for-virus-research/weeSAM#1]
I get the following error when running: weeSAM --bam tolBest.bam --html tolBest.html --out tolBest.sum.txt

Traceback (most recent call last):
  File "/software/bin/weeSAM", line 164, in <module>
    pysam.index(args.bam)
  File "/usr/local/lib/python3.6/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: failed to create or write index\n'

**Comment by josephhughes** [comment]
This is connected to the presence of an index file already there. Use the index file if already there if not create it.

**Comment by ZackBoyd123** [comment]
Script now checks whether the bam index file exists. 
If it does not it pysam will build one. 
Will leave open until it's been tested some more.

**Comment by josephhughes** [comment]
Looks good.
