### ISSUE TITLE
Multiple bam files

### ISSUE THREAD

**Issue by josephhughes** [centre-for-virus-research/weeSAM#4]
It would be good if we could do this for a list of bam files as an enhancement: file1.bam,file2.bam,file3.bam
This will mean that you will need to label the table with a column file name and as multiple files might have the same reference name, the figures will need a name that combines the filename and the reference name.

**Comment by ZackBoyd123** [comment]
This has been added.
Bam or Sam inputs must be separated by a comma like so:  

`` weeSAM --bam /my/dir/file1.bam,~/file2.bam,file3.bam --out test.txt `` 

File names are now the first column in the table.
