### ISSUE TITLE
Issue with having / character in sequence name

### ISSUE THREAD

**Issue by rjorton** [centre-for-virus-research/weeSAM#5]
If you have a / in seq name, seems to be looking using that as a file path

Total # Mapped Reads:	191
Total # Unmapped Reads:	145873
Total # Reads:	146064
Processing:	242845-B/Russia/69_Yamagata_NP	....
Traceback (most recent call last):
  File "/software/bin/weeSAM", line 388, in <module>
    fig.savefig(str(save_path)+str(i) + ".svg", format="svg")
  File "/usr/local/lib/python3.6/site-packages/matplotlib/figure.py", line 2035, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/backend_svg.py", line 1195, in print_svg
    with cbook.open_file_cm(filename, "w", encoding="utf-8") as fh:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 624, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 609, in to_filehandle
    fh = io.open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: '075C_Ribo_Tru_SSIII_fluB_html_results/075C_Ribo_Tru_SSIII_fluB_figures/242845-B/Russia/69_Yamagata_NP.svg'

**Comment by rjorton** [comment]
The seq name is: >242845-B/Russia/69_Yamagata_NP

**Comment by rjorton** [comment]
This is quite a big issue. A large number of sequences on Genbank have the / in their seq name 

e.g.
>KY786027.1 Ebola virus strain Ebola virus/M.fascicularis-wt/GAB/2001/untreated-CCL053D9, complete genome

as weesam uses the ref name folder name to store figures it creates a file/folder not found error

weeSAM --bam ebola.bam --html file.html --out out.txt

FileNotFoundError: [Errno 2] No such file or directory: 'file_html_results/file_figures/KY786027.1 Ebola virus strain Ebola virus/M.fascicularis-wt/GAB/2001/untreated-CCL053D9, complete genome.svg'

**Comment by ZackBoyd123** [comment]
I had a shot at recreating this back home. Is sequence name dependent on which alignment software was used? I used BT2 with that genbank entry (KY786027.1) and it automatically trimmed the sequence name after the first space. 
You're spot on with what the problem is however, I could change the script to change all forward slashes to underscores or trim the sequence name after the first occurrence. This would most likely fix the problem but I would need to find out which alignment software was used so I can test it more thoroughly.

**Comment by rjorton** [comment]
tanoti will use the full name:

KY786027.1 Ebola virus strain Ebola virus/M.fascicularis-wt/GAB/2001/untreated-CCL053D9, complete genome

But got given some flu that were like:

>242845-B/Russia/69_Yamagata_NP

In which case bwa (and presumably all) uses everything

**Comment by ZackBoyd123** [comment]
I've changed the code so that it deals with slash and space characters within sequence names now.

**Comment by rjorton** [comment]
Issue with this ref:

>NC_004102.1 Hepatitis C virus genotype 1, complete genome

Firefox can't find the file at /home1/orto01r/Projects/Cambridge2019/Test/HCV/1a_html_results/1a_figures/NC_004102.1.

**Comment by josephhughes** [comment]
I think you need to replace the spaces with underscore as well. I don't know of any assembler beside tanoti that take the full description line as the reference name.

**Comment by ZackBoyd123** [comment]
The current version of the code replaces spaces and slashes.
Here's the html file it generated when I used the above reference  

`` ./weeSAM --sam hepc_tanoti.sam --html test.txt``
**/home/zack/Bioinformatics_software/weeSAM_test/test_html_results/figures/hepc_tanoti_figures/NC_004102.1_Hepatitis_C_virus_genotype_1,_complete_genome.html**

Is there any chance that you pulled the version which was added when I accidentally deleted the repository (these didn't have the changes added)?
