### ISSUE TITLE
Breadth and % covered statistics incorrect

### ISSUE THREAD

**Issue by rjorton** [centre-for-virus-research/weeSAM#7]
The breadth and % covered statistic are incorrect.

I believe this is a result of using the -a argument on samtools depth, but the breadth and %covered statistics rely on the sites with 0 coverage not being there

**Comment by rjorton** [comment]
i.e. it will always say 100% breadth, even if very few sites covered

**Comment by mvvucak** [comment]
Latest push should have fixed it. Let me know if has.
